# Generated by Django 4.0.5 on 2023-11-10 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(blank=True, max_length=512, null=True, verbose_name='introduction')),
                ('position', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BioSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('github', 'Github'), ('linkedin', 'Linkedin')], max_length=16)),
                ('link', models.CharField(max_length=64, null=True)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='bio.bio')),
            ],
        ),
        migrations.CreateModel(
            name='BioSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_proficient', models.BooleanField(default=True, verbose_name='is proficient')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio.bio')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skill')),
            ],
        ),
        migrations.CreateModel(
            name='BioHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=5, null=True)),
                ('description', models.CharField(max_length=256)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='bio.bio')),
            ],
        ),
        migrations.CreateModel(
            name='BioExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=64)),
                ('responsibility', models.JSONField()),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='bio.bio')),
            ],
        ),
        migrations.AddField(
            model_name='bio',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='bio_skills', through='bio.BioSkill', to='skill.skill'),
        ),
        migrations.AddField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bio', to=settings.AUTH_USER_MODEL),
        ),
    ]
