name: SonarQube Scan
on:
  push:
    branches:
      - "master"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "master"


jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Run Unit Test
      # if: github.event_name = 'pull_request'
      run: |
        docker-compose -f docker-compose.test.yml run app sh bin/dj-test.sh
    #     sed -i 's/\/home\/runner\/work\/${{github.event.repository.name}}\/${{github.event.repository.name}}\///g' coverage.xml
      continue-on-error: true

    - name: Fix code coverage paths
      # if: github.event_name = 'pull_request'
      run: |
        sed -i 's#<source>/app</source>#<source>/github/workspace/src</source>#' src/coverage.xml
      continue-on-error: true

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.python.coverage.reportPaths=src/coverage.xml
          -Dsonar.scm.exclusions.disabled=true
          -Dsonar.verbose=true
          -Dsonar.sources=.
